name: SoundSearch
author: Anarchick
description: 'Better than searching using /playsound'
version: 1.0
api-version: 1.13
main: fr.anarchick.soundsearch.Main
depend: []
softdepend: []
commands:
   soundsearch:
      description: Search a sound using regex
      usage: /soundsearch [name] [group]
      permission: soundsearch.use